feat: brought types
sqwoteg/jobana_rusnia pull request #1
Opened 2022-11-20 23:17 UTC by bogdanbpeterson

2022-11-20 23:59 UTC, bogdanbpeterson commented
ede3c0ee7e7cb5c246c3626c8bf554e3f8647c18 resolves #3

2022-11-21 07:26 UTC, sqwoteg requested changes

2022-11-21 07:26 UTC, sqwoteg commented on src/utils/contains-ruzzniy.ts
> +const jobanaruzznia =
camelCase

2022-11-21 07:26 UTC, sqwoteg commented on prisma/schema.prisma
> +  encounters Int @default(0)
why did you rename second prop?

2022-11-21 07:26 UTC, sqwoteg commented on prisma/schema.prisma
> +  chatId Int @id @unique
You should use BigInt there or it will break in some chats

2022-11-21 07:26 UTC, sqwoteg commented on src/index.ts
> +import { jobanaruzzniaFileId } from './config/jobana-ruzznia-animation';
jobanaAnimationFileId
jobanaAnimation

2022-11-21 07:26 UTC, sqwoteg commented on src/index.ts
> +    ctx.reply('Додай мене в групу і почніть їбати русню');
Add different text if it is a group

2022-11-21 07:26 UTC, sqwoteg commented on src/index.ts
> +    // handle help command
Useless comment

2022-11-21 07:26 UTC, sqwoteg commented on src/index.ts
> +    ctx.reply('Додай мене в групу і почніть їбати русню');
Add different text if it is a group

2022-11-21 07:26 UTC, sqwoteg commented on src/index.ts
> +      ctx.reply('Пробач, але я працюю тільки в групах 🥺');
But why?

2022-11-21 07:26 UTC, sqwoteg commented on src/index.ts
> +import { containsruzzniu } from './utils/contains-ruzzniy';
Make it a default export

2022-11-21 07:26 UTC, sqwoteg commented on src/index.ts
> +import { containsruzzniu } from './utils/contains-ruzzniy';
Also, what do you think about renaming it to "contains🐷🐶"?

2022-11-21 07:26 UTC, sqwoteg commented on src/index.ts
> +          `Вітаю! Ваша подорож русофобією розпочалася! ₚусня йобана ${encounters} ${timesPluralized}`
Add a linebreak between sentenses

2022-11-21 07:26 UTC, sqwoteg commented on src/utils/contains-ruzzniy.ts
> +const jobanaruzznia =
maybe jobanaExpression will fit better cause you will not write rusnia with a big "R"

2022-11-21 07:28 UTC, bogdanbryzh commented on src/utils/contains-ruzzniy.ts
> +const jobanaruzznia =
oky

2022-11-21 07:28 UTC, bogdanbryzh commented on prisma/schema.prisma
> +  encounters Int @default(0)
it's more semantically correct

2022-11-21 07:29 UTC, bogdanbryzh commented on prisma/schema.prisma
> +  chatId Int @id @unique
will fix, oky

2022-11-21 07:29 UTC, bogdanbryzh commented on src/index.ts
> +    ctx.reply('Додай мене в групу і почніть їбати русню');
makes sense

2022-11-21 07:31 UTC, bogdanbryzh commented on src/index.ts
> +      ctx.reply('Пробач, але я працюю тільки в групах 🥺');
it doesn't make any sense to do it alone 
we have to encourage people to unite on this

2022-11-21 07:32 UTC, bogdanbryzh commented on src/index.ts
> +import { containsruzzniu } from './utils/contains-ruzzniy';
i prefer not to use default exports unless it's unavoidable

2022-11-21 07:40 UTC, sqwoteg commented on src/index.ts
> +import { containsruzzniu } from './utils/contains-ruzzniy';
Or if not, rename it co containsJobana

2022-11-21 09:27 UTC, sqwoteg commented on src/config/jobanaAnimation.ts
> +export const jobanaruzzniaFileId =
jobanaFileId

camelCase pls

2022-11-21 09:27 UTC, sqwoteg commented on src/utils/containsPiggoDoggos.ts
> +export const containsPiggoDogges = (text: string) => {
I meant real emojis

If no, lets name it containsJobana

2022-11-21 09:27 UTC, sqwoteg commented on src/utils/isChatPrivate.ts
> +export const isChatPrivate = (chat: TelegrafChat) => chat.type === 'private';
maybe unite isChatGroup and isChatPrivate into one file?

2022-11-21 09:29 UTC, bogdanbpeterson commented on src/utils/containsPiggoDoggos.ts
> +export const containsPiggoDogges = (text: string) => {
emojis doesn't work, will change to `Jobana`

2022-11-21 09:30 UTC, sqwoteg commented on src/utils/isChatPrivate.ts
> +export const isChatPrivate = (chat: TelegrafChat) => chat.type === 'private';
chatUtils.ts maybe

2022-11-21 09:35 UTC, bogdanbpeterson commented on src/utils/isChatPrivate.ts
> +export const isChatPrivate = (chat: TelegrafChat) => chat.type === 'private';
I'd insist on current state, I prefer each function in it's own file. Sometimes might be cluttering, but `ctrl + p` thank you

2022-11-21 09:36 UTC, sqwoteg commented on src/utils/isChatPrivate.ts
> +export const isChatPrivate = (chat: TelegrafChat) => chat.type === 'private';
ok

2022-11-21 09:39 UTC, sqwoteg approved these changes

2022-11-21 09:40 UTC, merged